from typing import Optional, Protocol, runtime_checkable


@runtime_checkable
class AuthSessionDao(Protocol):
    async def store_refresh_token(self, token: str, user_id: int, ttl: int) -> None: ...

    async def get_user_id_by_refresh_token(self, token: str) -> Optional[int]: ...

    async def revoke_refresh_token(self, token: str) -> None: ...

    async def get_and_revoke_refresh_token(self, token: str) -> Optional[int]: ...

    async def revoke_all_user_tokens(self, user_id: int) -> None: ...

    async def reserve_password_reset_request(self, identity_hash: str, ttl: int) -> bool: ...

    async def increment_password_reset_attempts(self, identity_hash: str, ttl: int) -> int: ...

    async def clear_password_reset_attempts(self, identity_hash: str) -> None: ...

    async def acquire_password_reset_lock(
        self, identity_hash: str, token: str, ttl: int
    ) -> bool: ...

    async def release_password_reset_lock(self, identity_hash: str, token: str) -> None: ...
