"""Dependency-free database constraint definitions shared by models and migrations."""

from typing import Final

REFERRAL_REWARDS_DURABLE_STATE_CONSTRAINT_NAME: Final[str] = "ck_referral_rewards_durable_state"
REFERRAL_REWARDS_DURABLE_STATE_CONSTRAINT_SQL: Final[str] = (
    "((state = 'ISSUED' AND is_issued AND issued_at IS NOT NULL "
    "AND processing_token_hash IS NULL AND processing_lease_expires_at IS NULL) OR "
    "(state = 'PROCESSING' AND NOT is_issued "
    "AND processing_token_hash IS NOT NULL "
    "AND processing_lease_expires_at IS NOT NULL) OR "
    "(state IN ('PENDING', 'RETRY_WAITING', 'SUPERSEDED') "
    "AND NOT is_issued AND processing_token_hash IS NULL "
    "AND processing_lease_expires_at IS NULL) OR "
    "(state = 'MANUAL_REQUIRED' AND processing_token_hash IS NULL "
    "AND processing_lease_expires_at IS NULL "
    "AND ((NOT is_issued) OR (is_issued AND issued_at IS NOT NULL)))) AND "
    "((target_expire_at IS NULL AND baseline_expire_at IS NULL "
    "AND target_subscription_id IS NULL) OR "
    "(type = 'EXTRA_DAYS' AND target_expire_at IS NOT NULL "
    "AND baseline_expire_at IS NOT NULL AND target_subscription_id IS NOT NULL)) "
    "AND ((source_transaction_id IS NULL AND origin_referral_id IS NULL "
    "AND level IS NULL AND accrual_strategy_snapshot IS NULL "
    "AND accrual_strategy IS NULL AND reward_strategy IS NULL "
    "AND config_value IS NULL "
    "AND state IN ('ISSUED', 'MANUAL_REQUIRED', 'SUPERSEDED')) OR "
    "(source_transaction_id IS NOT NULL AND origin_referral_id IS NOT NULL "
    "AND level IS NOT NULL AND accrual_strategy_snapshot IS NOT NULL "
    "AND reward_strategy IS NOT NULL AND config_value IS NOT NULL "
    "AND ((accrual_strategy_snapshot = 'ON_FIRST_PAYMENT' "
    "AND (accrual_strategy IS NULL OR accrual_strategy = 'ON_FIRST_PAYMENT')) "
    "OR (accrual_strategy_snapshot = 'ON_EACH_PAYMENT' "
    "AND accrual_strategy = 'ON_EACH_PAYMENT'))))"
)
